version: "3"

services:
  frontend:
    image: "nub31/vscode-vs-theme-converter:frontend"
    ports:
      - "3004:3004"
    environment:
      FRONTEND_PORT:
      EMAIL_EMAIL:
      EMAIL_PASSWORD:
    restart: always
  backend:
    image: "nub31/vscode-vs-theme-converter:backend"
    ports:
      - "3003:3003"
    restart: always
    environment:
      BACKEND_PORT:
      API_PUBLIC_URL:
      CLIENT_PUBLIC_URL:
